### ISSUE TITLE
Add option to expose all string attributes as info metrics.

### ISSUE THREAD

**Issue by eiiches** [eiiches/scriptable-jmx-exporter#17]
It might be useful as long as it doesn't cause too much load on Prometheus.

```yaml
# TODO: come up with a better API
declarations:
   public static final V1.Config config = V1.config()
       .stringAsInfoMetrics(true)
       .snakeCase();

rules:
- transform: |
    V1.transform(..., config);
```
